# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9967c78d124f6918b63fec2e2a3b9c3a46fbee090b9ded691dcc8081ff00fbaacce0e3970814bdf64d0a916aa64e6b9aa99f841a93b1578232bc1656b4e55096

test:
  secret_key_base: 7e53eb6f9bd968518d40388019f63c97f4b02b4631f16307d98e420a094c54038c56fc359e7782b02f4ee13b04de9c71b1e6355c7b82891165e2d17e4a79df7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
